### ISSUE TITLE
It got stuck in pre-flight request

### ISSUE THREAD

**Issue by imrvshah** [aaronksaunders/ionic2-graphql-apollo-client#1]
Hi, 

I am tried to test the example on my machine but it got stuck in a pre-flight request. 
Please see the screenshot. 
https://screencast.com/t/iHSnpC33

**Comment by aaronksaunders** [comment]
that looks like a 404 error? i would suggest cloning my server, and making sure you have set the proper CORS host ip address

**Comment by ronaldofreitas** [comment]
how to clone your server?

**Comment by aaronksaunders** [comment]
@ronaldofreitas click the remix button on the page

**Comment by sasharevzin** [comment]
@imrvshah seems like the issue was with an endpoint: https://github.com/aaronksaunders/ionic2-graphql-apollo-client/pull/2
